name: nostr-rs-relay
services:
  nostr-rs-relay:
    image: scsibug/nostr-rs-relay:latest
    cpu_shares: 10
    container_name: nostr-rs-relay
    deploy:
      resources:
        reservations:
          memory: 64M
        limits:
          memory: 1024M
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    hostname: nostr-rs-relay
    network_mode: bridge
    ports:
      - target: 8080
        published: "7000"
        protocol: tcp
    restart: unless-stopped
    user: $PUID:$PGID
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config.toml
        target: /usr/src/app/config.toml
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /usr/src/app/db
    x-casaos:
      ports:                 # description of each port
        - container: "8080"
          description:
            en_us: "Nostr-rs-relay will listen to incoming requests on the port 8080"
      volumes:               # description of each volume
        - container: /usr/src/app/config.toml
          description:
            en_us: "Nostr-rs-relay configuration file"
        - container: /usr/src/app/db
          description:
            en_us: "Nostr-rs-relay database for storing notes and other stuff transmitted by relays"
x-casaos:
  architectures:             # a list of architectures that the app supports
    - amd64
  author: Frank Seesink
  category: Network
  description:
    en_us: |
      This is a nostr relay, written in Rust. It currently supports the entire relay protocol, and persists data with SQLite. There is experimental support for Postgresql.

      By default Nostr-rs-relay will use port `7000`. If you want to use change this, then you have first to change the WebUI port of CasaOS first under the settings in the top left menu. After deploying the container you can change the host port mapping to match whatever new port you chose.

      Visit [Nostr-rs-relay](https://github.com/scsibug/nostr-rs-relay) for more details.
  developer: Greg Heartsfield
  icon: https://raw.githubusercontent.com/fseesink/CasaOS-AppStore/refs/heads/main/Apps/Nostr-rs-relay/icon.png
  index: /
  main: nostr-rs-relay       # the name of the main service under `services`
  port_map: "7000"
  project_url: https://github.com/fseesink/CasaOS-AppStore
  screenshot_link:
    - https://raw.githubusercontent.com/fseesink/CasaOS-AppStore/refs/heads/main/Apps/Nostr-rs-relay/screenshot-1.png
  tagline:
    en_us: |
      This is a nostr relay, written in Rust. It currently supports the entire relay protocol, and persists data with SQLite. There is experimental support for Postgresql.
  thumbnail: https://raw.githubusercontent.com/fseesink/CasaOS-AppStore/refs/heads/main/Apps/Nostr-rs-relay/icon.png
  tips:
    before_install:
      en_us: |
        By default Nostr-rs-relay will use port `7000`. If you want to use another port, then you have first to change the WebUI port of CasaOS first under the settings in the top left menu. After deploying the container you can change the host port mapping to match whatever new port you chose.

        [Website](https://github.com/scsibug/nostr-rs-relay) &bull;
  title:
    en_us: Nostr-rs-relay
