name: traefik
services:
  traefik:
    image: traefik:v3.4.1
    cpu_shares: 10
    container_name: traefik
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 1024M
    environment:
      - DNS_API_KEY=<set correct environment variable name and value here>
      - PGID=$PGID
      - PUID=$PUID
      - TRAEFIK_API=false
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_API_INSECURE=false
      - TZ=$TZ
    hostname: traefik
    network_mode: host
    ports:
      - target: 80
        published: "81"
        protocol: tcp
      - target: 443
        published: "443"
        protocol: tcp
      - target: 8080
        published: "8080"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/traefik.yml
        target: /etc/traefik/traefik.yml
      - type: bind
        source: /DATA/AppData/$AppID/acme.json
        target: /etc/traefik/acme.json
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /DATA/AppData/$AppID/file-provider.yml
        target: /dynamic/conf/file-provider.yml
    x-casaos:
      envs:                  # description of each environment variable
        - container: DNS_API_KEY
          description:
            en_us: "The particular ACME provider environment var from https://doc.traefik.io/traefik/https/acme/#providers"
        - container: PGID
          description:
            en_us: "User that Traefik runs as"
        - container: PUID
          description:
            en_us: "Group that Traefik runs under"
        - container: TRAEFIK_API
          description:
            en_us: "Enable API/dashboard. (Default: false)"
        - container: TRAEFIK_API_DASHBOARD
          description: 
            en_us: "Activate dashboard. (Default: true)"
        - container: TRAEFIK_API_INSECURE
          description:
            en_us: "Activate API directly on the entryPoint named traefik. (Default: false)"
        - container: TZ
          description:
            en_us: "Time zone used (Default: system)"
      ports:                 # description of each port
        - container: "80"
          description:
            en_us: "Traefik will listen to incoming request on the port 80 (HTTP)"
        - container: "443"
          description:
            en_us: "Traefik will listen to incoming request on the port 443 (HTTPS)"
        - container: "8080"
          description:
            en_us: "Traefik will listen on port 8080 by default for API request."
      volumes:               # description of each volume
        - container: /etc/traefik/traefik.yml
          description:
            en_us: "Traefik static configuration file"
        - container: /etc/traefik/acme.json
          description:
            en_us: "ACME (Let's Encrypt) file for certificate storage"
        - container: /var/run/docker.sock
          description:
            en_us: "Specifies the Docker API endpoint."
        - container: /dynamic/conf/file-provider.yml
          description:
            en_us: "Traefik dynamic configuration file (where routers and services are stored)"
x-casaos:
  architectures:             # a list of architectures that the app supports
    - amd64
    - arm
    - arm64
    - ppc64le
  author: Frank Seesink
  category: Network
  description:
    en_us: |
      Traefik allows you to access multiple containers on the same IP via port HTTP/HTTP and hostnames. Since Traefik reads the Docker containers it automatically searches for an open port and makes it available.

      By default Traefik will use port `81` for `HTTP`, port `443` for `HTTPS` and port `8080` for the dashboard. If you want to use port `80` for `HTTP`, then you have first to change the WebUI port of CasaOS first under the settings in the top left menu. After deploying the container you can change the port mapping from `81` to `80`.

      Visit [Traefik Labs](https://doc.traefik.io/traefik/) for more details. Check the [documentation](https://doc.traefik.io/traefik/) for further settings.

      🚨 Note: This app will always stay on the latest version of 2.x. If you want to upgrade always to the latest version install `Traefik` instead.
  developer: Traefik Labs
  icon: https://icon.casaos.io/main/all/traefik.png
  index: /
  main: traefik              # the name of the main service under `services`
  port_map: "8080"
  project_url: https://github.com/fseesink/CasaOS-AppStore
  screenshot_link:
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Traefik-v3/screenshot-1.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Traefik-v3/screenshot-2.png
    - https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Traefik-v3/screenshot-3.png
  tagline:
    en_us: |
      Traefik is the leading open-source reverse proxy and load balancer for HTTP and TCP-based applications that is easy, dynamic and full-featured.
  thumbnail: https://raw.githubusercontent.com/mr-manuel/CasaOS-HomeAutomation-AppStore/latest/Apps/Traefik-v3/icon.png
  tips:
    before_install:
      en_us: |
        By default Traefik will use port `81` for `HTTP`, port `443` for `HTTPS` and port `8080` for the dashboard. If you want to use port `80` for `HTTP`, then you have first to change the WebUI port of CasaOS first under the settings in the top left menu. After deploying the container you can change the port mapping from `81` to `80`.

        To leverage ACME Let's Encrypt service, you likely will need to set an environment variable for your particular DNS provider.  More details [here](https://doc.traefik.io/traefik/https/acme/#providers).

        [Website](https://traefik.io) &bull; [Documentation](https://doc.traefik.io/traefik/v3.0)
  title:
    en_us: Traefik v3
